In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
type(myarray)

numpy.ndarray

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)

In [15]:
arr.min()

np.int32(9)

In [16]:
arr.argmin()

np.int64(7)

In [17]:
arr.mean()

np.float64(60.8)

In [18]:
mat = np.arange(0, 100).reshape(10, 10)

In [21]:
mat.shape

(10, 10)

In [22]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
row = 5
col = 9

In [29]:
mat[row, col]

np.int64(59)

In [30]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [31]:
mat[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])